# -*- coding: utf-8 -*-
"""streamlit bro

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ubDjMrcziFKT4amS8cC9m4WsWq14NEBJ
"""

# !pip install Streamlit

import streamlit as st
x=[]
y=[]
z=[]
start=st.text_input("Start from","write here")

corr=st.text_input("Correction","write here")

corr_ann=st.text_input("Correction d'annoteur","write here")

lab=st.selectbox("Label" ,['a','b','c'])

col1, col2, col3 = st.columns(3)


if col1.button('Delete'):
  x="hjfkjbgfh"
elif col2.button('Save'):
  y="jhdrjgdj"
elif col3.button('Next'):
  z="jgfjgj"

